version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3 -m venv venv
          source ./venv/bin/activate
          # pytestのインストール
          pip install pytest
          # pytestコマンドの実行
          pytest test_calculations.py --junit-xml=test-results/pytest.xml
      # テスト結果を保存する
      - store_test_results:
          path: test-results
